version: '3.8'

services:
  # Database Service 
  mongodb:
    image: mongo:latest
    container_name: mongodb_service
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    networks:
      - mern-network

  # Backend Service 
  backend:
    image: todobackend:latest
    container_name: backend_service
    ports:
      - "8000:8000"
    environment:
      
      - MONGO_URI=mongodb://admin:password@mongodb:27017/todoapp?authSource=admin
    depends_on:
      - mongodb
    networks:
      - mern-network

  # Frontend Service 
  frontend:
    image: todofrontend:latest
    container_name: frontend_service
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - mern-network

networks:
  mern-network:
    driver: bridge